# Generated by Django 3.1.4 on 2021-01-02 00:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comentarios', '0002_auto_20210101_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='data_comentario',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 2, 0, 32, 24, 14444, tzinfo=utc), verbose_name='Data do comentário'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='utilizador_comentario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
